export const baseURL = 'https://jewel.cmsandbox.com.ng'
export const RegisterAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/register'
export const LoginAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/login'
export const MenusAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/menu/all'
export const VendorsAPI = 'https://jewel.cmsandbox.com.ng/api/vendors/all'
export const CreateOrderAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/order/new'
export const GetOrderAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/orders'
export const VendorMenuAPI = 'https://jewel.cmsandbox.com.ng/api/vendor/menu'  // -> /{id}
export const UpdateProfileAPI = 'https://jewel.cmsandbox.com.ng/api/buyer/profile'  // -> /{id}
export const PaystackKey = 'pk_test_4e4d75a86f6c6eb34aa43963d0d6d2179d3d0594'